### ISSUE TITLE
Error loading CBC add-on

### ISSUE THREAD

**Issue by figrn** [learningit/plugin.video.cbc#2]
CBC add-on fails to start. Captured the following trace from debug:

06:50:28 T:1334267584   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.cbc/)
06:50:28 T:1334267584   DEBUG:   ParentPath = [addons://sources/video]
06:50:28 T:1478599488   DEBUG: bool XFILE::CPluginDirectory::StartScript(const string&, bool) - calling plugin Canadian Broadcasting Corporation('plugin://plugin.video.cbc/','12','')
06:50:28 T:1478599488   DEBUG: bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool) - waiting on the Canadian Broadcasting Corporation (id=14) plugin...
06:50:28 T:1523454512  NOTICE: Thread LanguageInvoker start, auto delete: false
06:50:28 T:1523454512    INFO: initializing python engine.
06:50:28 T:1523454512   DEBUG: CPythonInvoker(14, /storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py): start processing
06:50:28 T:1523454512  NOTICE: -->Python Interpreter Initialized<--
06:50:28 T:1523454512   DEBUG: CPythonInvoker(14, /storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py): the source file to load is "/storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py"
06:50:28 T:1523454512   DEBUG: CPythonInvoker(14, /storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py): setting the Python path to /storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc:/:/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python26.zip:/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python2.6:/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python2.6/plat-linux3:/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python2.6/lib-tk:/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python2.6/lib-old:/data/app/org.xbmc.kodi-1.apk/assets/python2.6/lib/python2.6/lib-dynload
06:50:28 T:1523454512   DEBUG: CPythonInvoker(14, /storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py): entering source directory /storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc
06:50:28 T:1523454512   DEBUG: CPythonInvoker(14, /storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py): instantiating addon using automatically obtained id of "plugin.video.cbc" dependent on version 2.1.0 of the xbmc.python api
06:50:28 T:1523454512   DEBUG: Canadian Broadcasting Corporation: getRequest URL:http://www.cbc.ca/player/
06:50:29 T:1334267584   DEBUG: ------ Window Init (DialogBusy.xml) ------
06:50:29 T:1523454512   DEBUG: Canadian Broadcasting Corporation: getRequest URL:http://www.cbc.ca/player/
06:50:29 T:1334267584   DEBUG: Unfocus WindowID: 10025, ControlID: 551
06:50:29 T:1523454512   DEBUG: Canadian Broadcasting Corporation: Content Encoding == gzip
06:50:29 T:1523454512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py", line 276, in <module>
                                                if mode==  None:  getSources(p('fanart'))
                                              File "/storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py", line 107, in getSources
                                                html = re.compile('<div id="catnav">(.+?)<div id="cliplist">').search(html).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
06:50:29 T:1523454512    INFO: Python script stopped
06:50:29 T:1523454512   DEBUG: Thread LanguageInvoker 1523454512 terminating
06:50:29 T:1478599488   DEBUG:  bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool) - plugin exited prematurely - terminating
06:50:29 T:1334267584   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.cbc/
06:50:29 T:1334267584   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cbc/) failed
06:50:29 T:1334267584   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/video)

**Comment by learningit** [comment]
Please DO NOT post debug logs here. Use pastebin or xbmclogs. Actually don't post problems here - use the Kodi forum -  http://forum.kodi.tv/showthread.php?tid=222347 
This problem is known see the forum.
